# Generated by Django 3.1.5 on 2021-01-26 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rasma', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rasma',
            name='id_set',
        ),
        migrations.RemoveField(
            model_name='rasma',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='rasmaimage',
            name='id_set',
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rasma',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='rasma',
            name='last_modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rasma',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rasma',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='rasma',
            name='version',
            field=models.FloatField(default=1),
        ),
    ]
