# Generated by Django 3.1.5 on 2021-01-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasma', '0002_auto_20210126_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasma',
            name='data',
            field=models.TextField(),
        ),
    ]
