# Generated by Django 3.1.5 on 2021-01-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasma', '0003_auto_20210126_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasma',
            name='version',
            field=models.FloatField(),
        ),
    ]
